APP_KEY = 'Mh75kqXJjFSKFVkoXK0A5g'
APP_SECRET = 'LNCGgondtJO16hdKzbNjB2PVWE0IMHoGxMEojpi78QI'
AUTH_URL = 'https://api.twitter.com/oauth2/token'
GET_USER_URL = 'https://api.twitter.com/1.1/users/show.json'
BATCH_GET_USER_URL = 'https://api.twitter.com/1.1/users/lookup.json'